version: '3.8'

services:
  deys0:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        DISABLE_READ_API: "false"
        DISABLE_WEBAPP: "false"
        DISABLE_WRITE_API: "false"
        CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        WOBSERVER_ENABLED: "false"
        ADMIN_PANEL_ENABLED: ""
    restart: always
    environment:
      - DEYES_CONFIG_PATH=/app/deyes.toml
    stop_grace_period: 5m
    container_name: 'deyes0'
    ports:
      - 9091:9091
    volumes:
      - ./deyes0.toml:/app/deyes.toml
  deys1:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        DISABLE_READ_API: "false"
        DISABLE_WEBAPP: "false"
        DISABLE_WRITE_API: "false"
        CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        WOBSERVER_ENABLED: "false"
        ADMIN_PANEL_ENABLED: ""
    environment:
      - DEYES_CONFIG_PATH=/app/deyes.toml
    restart: always
    stop_grace_period: 5m
    container_name: 'deyes1'
    ports:
      - 9081:9081
    volumes:
      - ./deyes1.toml:/app/deyes.toml